added maintenance note
byuoitav/smee pull request #25
Opened 2021-07-26 16:17 UTC by SamuelMR98

2021-07-26 16:22 UTC, SamuelMR98 commented
#25 Added Maintenance Note

2021-07-26 16:23 UTC, SamuelMR98 commented
#16 Added Maintenance Note

2021-07-27 20:27 UTC, bwinterton requested changes
This all looks awesome! There's just a couple of things to change and then we'll get it merged in.

2021-07-27 20:27 UTC, bwinterton commented on migrations/0001_initial_creation.up.sql
> +	end_time timestamptz IS NOT NULL,
I've already got these changes pushed up in master, can we remove these?

2021-07-27 20:27 UTC, bwinterton commented on website/src/app/api.service.ts
> +        console.log(info)
Let's remove this console.log

2021-07-27 20:36 UTC, bwinterton requested changes

2021-07-27 20:36 UTC, bwinterton commented on migrations/0001_initial_creation.up.sql
>  	end_time timestamptz IS NOT NULL,
Remove trailing comma here.

2021-07-27 21:28 UTC, bwinterton approved these changes
LGTM

2021-07-27 21:28 UTC, merged